### ISSUE TITLE
Unable to import API into ruby client 

### ISSUE THREAD

**Issue by bark-mshort** [commercetools/commercetools-api-reference#268]
I'm trying to generate a ruby client via OpenAPI Generator. We've used both the npm installation approach as well as the homebrew installation. When trying to generate the client via CLI, we run into a number of warnings and some errors that end up blocking file generation. 

#### Install CLI

```shell
brew install openapi-generator
```

#### Generate ruby client

```
openapi-generator generate -i \
https://raw.githubusercontent.com/commercetools/commercetools-api-reference/main/oas/openapi.yaml \
--additional-properties=gemName=hackathon_ct_sdk,moduleName=HackathonCtSdk -g ruby
```

### Errors

```
Exception in thread "main" org.openapitools.codegen.SpecValidationException: 
There were issues with the specification. The option can be disabled via validateSpec (Maven/Gradle) or --skip-validate-spec (CLI).
 | Error count: 80, Warning count: 210
```

The primary error seems to be 
```
        -Null key for a Map not allowed in JSON (use a converting NullKeySerializer?) (through reference chain: java.util.LinkedHashMap["components"]->java.util.LinkedHashMap["schemas"]->java.util.LinkedHashMap["Message"]->java.util.LinkedHashMap["allOf"]->java.util.ArrayList[1]->java.util.LinkedHashMap["discriminator"]->java.util.LinkedHashMap["mapping"]->java.util.LinkedHashMap["null"])
```

But there are also a bunch of missing schema errors too (unsure if it's related to the above error): 
`-attribute components.schemas.ReplicaMyCartDraft.items is missing`
`-attribute paths.'/{projectKey}/product-projections/search'(post).requestBody.content.'application/x-www-form-urlencoded'.schema.#/components/schemas/string is missing`

As is suggested by the generator, I appended to `--skip-validate-spec` to the generator command and all files successfully populate, but the classes in the newly created gem are failing to load: 

```
hackathon-ct-sdk main 18m ⍉ ➜ irb
irb(main):001:0> require 'hackathon_ct_sdk'
Traceback (most recent call last):
        .......
        .......
        2: from /Users/mirandashort/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/hackathon_ct_sdk-1.0.0/lib/hackathon_ct_sdk/models/category_created_message.rb:16:in `<top (required)>'
        1: from /Users/mirandashort/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/hackathon_ct_sdk-1.0.0/lib/hackathon_ct_sdk/models/category_created_message.rb:17:in `<module:HackathonCtSdk>'
NameError (uninitialized constant HackathonCtSdk::Message)
Did you mean?  HackathonCtSdk::MessageAllOf
```

Could this be an issue with the spec?

**Comment by jenschude** [comment]
The OAS definition is generated. I ran it through a validator and found some smaller issues. I fixed it in a branch https://github.com/commercetools/commercetools-api-reference/compare/oas_fix

Can't merge it as before the code generator has to be adjusted

**Comment by jenschude** [comment]
I fixed the issues in the generator and the OpenApi spec file is now valid

**Comment by jenschude** [comment]
Ah there is a small error still inside.

Could you just remove line 76330

```
              InventoryEntryQuantitySet: '#/components/schemas/InventoryEntryQuantitySetMessage'
              null: '#/components/schemas/OrderMessage'         # <---- this line here
              OrderPaymentAdded: '#/components/schemas/OrderPaymentAddedMessage'
```

**Comment by bark-mshort** [comment]
Same error - looks like the last thing that runs before I do receive the error is for `ZoneAddLocationAction_allOf`

**Comment by bark-mshort** [comment]
Correction - it is a different error but seems to still be caused by a request body: 

```
  Exception: Request body cannot be null. Possible cause: missing schema in body parameter (OAS v2): class RequestBody {
    description: null
    content: class Content {
        {*/*=class MediaType {
            schema: null
            examples: null
            example: null
            encoding: null
        }}
    }
    required: null
}
        at org.openapitools.codegen.DefaultGenerator.processOperation(DefaultGenerator.java:1186)
        at org.openapitools.codegen.DefaultGenerator.processPaths(DefaultGenerator.java:1080)
        at org.openapitools.codegen.DefaultGenerator.generateApis(DefaultGenerator.java:571)
        at org.openapitools.codegen.DefaultGenerator.generate(DefaultGenerator.java:914)
        at org.openapitools.codegen.cmd.Generate.execute(Generate.java:465)
        at org.openapitools.codegen.cmd.OpenApiGeneratorCommand.run(OpenApiGeneratorCommand.java:32)
        at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:66)
Caused by: java.lang.RuntimeException: Request body cannot be null. Possible cause: missing schema in body parameter (OAS v2): class RequestBody {
    description: null
    content: class Content {
        {*/*=class MediaType {
            schema: null
            examples: null
            example: null
            encoding: null
        }}
    }
    required: null
```

**Comment by jenschude** [comment]
It was the issue with the image upload endpoint, that the code generator expected some body definition whereas the spec says it's valid to have no body type at all. 🤷 

Fixed it to be a string. Tried your command and it works now.

**Comment by jenschude** [comment]
Don't know what the openapi generator is creating there and i don't know enough of ruby to be of help here.

**Comment by bark-mshort** [comment]
Okay I can open an Issue with openapi and make sure it's not an issue with the ruby generator. Essentially it's not able to load the class `Message` (but I can confirm the model is there). I'll see if they can confirm whether or not it's an issue on the commercetools side or their side.
